c_compiler_version:     # [linux]
  - 7                   # [linux64 or aarch64]
  - 8                   # [ppc64le]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64 or aarch64]
  - 8                   # [ppc64le]
