{% set version = "0.14.2" %}

package:
  name: patchelf
  version: {{ version }}

source:
  url: https://github.com/NixOS/patchelf/releases/download/{{ version }}/patchelf-{{ version }}.tar.bz2
  sha256: 08bfea52ccf3e4e8b3dc5a6844bcecdde8e7d0a006160aec422d9af9c19e6079

build:
  number: 0
  skip: true  # [not linux]
  binary_relocation: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - bash -c '[[ "$(patchelf --version)" =~ "patchelf {{ version }}".* ]]'

about:
  home: http://nixos.org/patchelf.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: A small utility to modify the dynamic linker and RPATH of ELF executables.
  description: |
    PatchELF is a small utility to modify the dynamic linker and RPATH of ELF
    executables.
  doc_url: http://nixos.org/patchelf.html
  dev_url: https://github.com/NixOS/patchelf

extra:
  recipe-maintainers:
    - jakirkham
    - leofang
    - mjuric
    - xhochy
